In [1]:
## I have taken the use of tutorial Scikit learn ::::::  for futher reference

# https://www.youtube.com/watch?v=0Lt9w-BxKFQ

In [3]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from random import seed
from random import randint

In [4]:
from sklearn.ensemble import RandomForestClassifier

In [5]:
from sklearn.svm import SVC
from sklearn import svm
from sklearn.neural_network import MLPClassifier
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import StandardScaler


from sklearn.model_selection import train_test_split
%matplotlib inline 

In [6]:
from sklearn.metrics import confusion_matrix, classification_report
from sklearn.metrics import accuracy_score
from sklearn.exceptions import NotFittedError
from sklearn.impute import SimpleImputer

In [18]:
data = pd.read_csv("train.csv")
#data = pd.DataFrame(data)
#print(dfData.head())

data

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

# Data Processing

In [23]:
# Seperating the data into features and what is to be predicted
# Data preprocessing


"""
We can use .drop() to remove the specified cols and then use dummies to covert the named cols into 0s and 1s
and remove the rest

X = data.drop(['Survived', 'Ticket', 'Name'], axis =1)    
X = pd.get_dummies(X[features])

"""

# if we directly use get_dummies. It will convert the named cols into 0s & 1s, and automaticaly 
# remove the rest....

features = ["Pclass", "Sex", "SibSp", "Parch","Fare"]

X = pd.get_dummies(data[features])

Y = data['Survived']                                     # Y is the ground truth to be predicted

X

Pclass  SibSp  Parch     Fare  Sex_female  Sex_male
0         3      1      0   7.2500           0         1
1         1      1      0  71.2833           1         0
2         3      0      0   7.9250           1         0
3         1      1      0  53.1000           1         0
4         3      0      0   8.0500           0         1
..      ...    ...    ...      ...         ...       ...
886       2      0      0  13.0000           0         1
887       1      0      0  30.0000           1         0
888       3      1      2  23.4500           1         0
889       1      0      0  30.0000           0         1
890       3      0      0   7.7500           0         1

[891 rows x 6 columns]

In [24]:
# Splitting data into train and test set

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2, random_state = 42)
#X_train = X
#Y_train = Y

In [25]:
#Applying Feature scaling to Fare  :: Puting Feature Scaling of Age under trail

sc = StandardScaler()   # Standard Scaler
mms = MinMaxScaler()    # Min Max Scaler

X_test[['Fare']] = mms.fit_transform(X_test[['Fare']])
X_train[['Fare']] = mms.fit_transform(X_train[['Fare']])
X_train

/Users/samarpan/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:6: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  
/Users/samarpan/opt/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py:965: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[item] = s
/Users/samarpan/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:7: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

Pclass  SibSp  Parch      Fare  Sex_female  Sex_male
331       1      0      0  0.055628           0         1
733       2      0      0  0.025374           0         1
382       3      0      0  0.015469           0         1
704       3      1      0  0.015330           0         1
813       3      4      2  0.061045           1         0
..      ...    ...    ...       ...         ...       ...
106       3      0      0  0.014932           1         0
270       1      0      0  0.060508           0         1
860       3      2      0  0.027538           0         1
435       1      1      2  0.234224           1         0
102       1      0      1  0.150855           0         1

[712 rows x 6 columns]

# Using Random Forest Classifier

In [58]:
#predict  

rfc = RandomForestClassifier(n_estimators = 400)
rfc.fit(X_train, Y_train)

pred_rfc = rfc.predict(X_test)





In [59]:
# accuracy report
# pred_rfc uses the X_test and predicts vals of Y__test and we also have the Y-test(original) and we thus can 
# test them against each oter


print(accuracy_score(Y_test, pred_rfc))
#print(classification_report(Y_test, pred_rfc))
print(confusion_matrix(Y_test, pred_rfc))


0.7821229050279329
[[98  7]
 [32 42]]


# COURSE TO FINE testing to find out the ideal value of n_estimator

In [60]:
  ##### 15 seems to be the best for n_estimator
"""
report = []
estimator = []

i = 100
while(i <= 5000):
    if(i % 100 == 0):
        
        temp = i
        rfc = RandomForestClassifier(n_estimators = temp)
        rfc.fit(X_train, Y_train)
        pred_rfc = rfc.predict(X_test)
        report.append(accuracy_score(Y_test, pred_rfc)) 
        estimator.append(temp)
        
        i+=100
        


"""
     

'\nreport = []\nestimator = []\n\ni = 100\nwhile(i <= 5000):\n  if(i % 100 == 0):\n      \n      temp = i\n      rfc = RandomForestClassifier(n_estimators = temp)\n      rfc.fit(X_train, Y_train)\n      pred_rfc = rfc.predict(X_test)\n      report.append(accuracy_score(Y_test, pred_rfc)) \n      estimator.append(temp)\n      \n      i+=100\n      \n\n\n'

In [61]:
"""
plt.plot(estimator, report)
plt.show()
"""

'\nplt.plot(estimator, report)\nplt.show()\n'

 # Part to be submitted for Random Forest Classifier

In [62]:
"""
test_data = pd.read_csv("test.csv")




XX_test = pd.get_dummies(test_data[features])
#print(XX_test)

XX_test[['Fare']] = mms.transform(XX_test[['Fare']])


print(XX_test.isnull().sum())

                             # Y is the ground truth to be predicted


    
    
    
#rfc = RandomForestClassifier(n_estimators=15,max_features="sqrt",verbose=True)



my_imputer = SimpleImputer()
XX_test = my_imputer.fit_transform(XX_test)
print(X_test.shape)

#X_train = mms.fit_transform(X_train)
#rfc.fit(X_train, Y_train)

#print(XX_test)
predictions = rfc.predict(XX_test)

output = pd.DataFrame({'PassengerId': test_data.PassengerId, 'Survived': predictions})
output.to_csv('my_submission.csv', index=False)
print("Your submission was successfully saved!")

"""

'\ntest_data = pd.read_csv("test.csv")\n\n\n\n\nXX_test = pd.get_dummies(test_data[features])\n#print(XX_test)\n\nXX_test[[\'Fare\']] = mms.transform(XX_test[[\'Fare\']])\n\n\nprint(XX_test.isnull().sum())\n\n                             # Y is the ground truth to be predicted\n\n\n    \n    \n    \n#rfc = RandomForestClassifier(n_estimators=15,max_features="sqrt",verbose=True)\n\n\n\nmy_imputer = SimpleImputer()\nXX_test = my_imputer.fit_transform(XX_test)\nprint(X_test.shape)\n\n#X_train = mms.fit_transform(X_train)\n#rfc.fit(X_train, Y_train)\n\n#print(XX_test)\npredictions = rfc.predict(XX_test)\n\noutput = pd.DataFrame({\'PassengerId\': test_data.PassengerId, \'Survived\': predictions})\noutput.to_csv(\'my_submission.csv\', index=False)\nprint("Your submission was successfully saved!")\n\n'

# Support Vector Machine Model

In [63]:
# Prediction for SVM

svma = svm.SVC()
svma.fit(X_train, Y_train)
pred_svma = svma.predict(X_test)


In [64]:
# Accuracy Report

print(accuracy_score(Y_test, pred_svma))
print(confusion_matrix(Y_test, pred_svma))




0.7932960893854749
[[92 13]
 [24 50]]


# Part to be submitted for SVM 

In [ ]:
"""
test_data = pd.read_csv("test.csv")
XX_test = pd.get_dummies(test_data[features])

XX_test[['Fare']] = mms.transform(XX_test[['Fare']])

my_imputer = SimpleImputer()
XX_test = my_imputer.fit_transform(XX_test)

predictions = svma.predict(XX_test)

output = pd.DataFrame({'PassengerId': test_data.PassengerId, 'Survived': predictions})
output.to_csv('my_submission.csv', index=False)
print("Your submission was successfully saved!")

"""

# Neural Network Model

In [26]:
#Prediction

nn = MLPClassifier(hidden_layer_sizes = (6,6,6,6), max_iter = 5200, learning_rate_init = 0.005963268091810203)
nn.fit(X_train, Y_train)
predict_nn = nn.predict(X_test)


# NN Parameter tuning (turn the 4 cells after this one ) in run time

In [17]:
# Finding the best learning rate

""""

accuracy = 0
best_accuracy = 0
for i in range(100):
    upper_limit = -2     ## id we need vals bw 0.001 & 0.0001. (-3 and -4) #lower limit=-4 # upper_limit=-3
    lower_limit = -3
    r = np.random.rand() + lower_limit
    learn_rate = pow(10,r)
    
    nn = MLPClassifier(hidden_layer_sizes = (6,6,6,6), max_iter = 5200, learning_rate_init = learn_rate)
    nn.fit(X_train, Y_train)
    
    predict_nn = nn.predict(X_test)
    current_accuracy = accuracy_score(Y_test, predict_nn)
    accuracy = accuracy + current_accuracy
    
    if(current_accuracy > best_accuracy):
        best_accuracy = current_accuracy
        print("Best accuracy : " , best_accuracy, "Learning rate = ", learn_rate)

print("Average Accuracy : " , accuracy / 100)
    
""""

Best accuracy :  0.7988826815642458 Learning rate =  0.005528630639024399
Best accuracy :  0.8044692737430168 Learning rate =  0.0021237079662405015
Average Accuracy :  0.7801117318435763


In [ ]:
""""
Accuracy in range of different learning rates (outputs of the above cell):

0.0001 - 0.001. 
Best accuracy :  0.8044692737430168     achieved with     Learning rate =  0.00011919300400072946
Average Accuracy :  0.7807262569832412

0.001 - 0.01.
Best accuracy :  0.8044692737430168     achieved with     Learning rate =  0.005963268091810203
Average Accuracy :  0.7811173184357548

0.01 - 0.1  
Best accuracy :  0.7988826815642458     achieved with     Learning rate =  0.07769173150625004
Average Accuracy :  0.7713407821229056

0.1 - 1.   
Best accuracy :  0.7988826815642458      achieved with    Learning rate =  0.10339071838431943
Average Accuracy :  0.6638547486033524

In [121]:
"""
# find the best No of iterations ::

i = 100
accurate = []
iters = []

while(i<=10000):
    nn = MLPClassifier(hidden_layer_sizes = (6,6,6,6), max_iter = i)
    nn.fit(X_train, Y_train)
    predict_nn = nn.predict(X_test)
    
    accurate.append(accuracy_score(Y_test, predict_nn))
    iters.append(i)
    
    i+=10
"""   

'\n#No of iterations ::\n\ni = 100\naccurate = []\niters = []\n\nwhile(i<=10000):\n    nn = MLPClassifier(hidden_layer_sizes = (6,6,6,6), max_iter = i)\n    nn.fit(X_train, Y_train)\n    predict_nn = nn.predict(X_test)\n    \n    accurate.append(accuracy_score(Y_test, predict_nn))\n    iters.append(i)\n    \n    i+=10\n'

In [122]:
"""
plt.plot(iters, accurate)
#plt.show()
"""

In [27]:
# Accuracy Report

print(accuracy_score(Y_test, predict_nn))
print(confusion_matrix(Y_test, predict_nn))




0.7932960893854749
[[97  8]
 [29 45]]


# Part to be submitted for NN

In [22]:
test_data = pd.read_csv("test.csv")
XX_test = pd.get_dummies(test_data[features])

XX_test[['Fare']] = mms.transform(XX_test[['Fare']])

my_imputer = SimpleImputer()
XX_test = my_imputer.fit_transform(XX_test)

predictions = nn.predict(XX_test)

output = pd.DataFrame({'PassengerId': test_data.PassengerId, 'Survived': predictions})
output.to_csv('my_submission_nn.csv', index=False)
print("Your submission was successfully saved!")

Your submission was successfully saved!
